#!/bin/bash

protocol=$1
side=$2

if test "$side" == ""; then
    echo "usage: $0 protocol side"
    exit 1
    fi

gcc -o "$protocol/c/$side/$side" "$protocol/c/$side/$side.c" && "$protocol/c/$side/$side"